// AUTO-GENERATED by scripts/fetch-manga-covers.mjs at 2026-04-17T23:20:22.289Z.
// Do not edit by hand. Re-run the script to refresh.

export type MangaCover = {
  aniListId: number;
  titleRomaji: string | null;
  titleNative: string | null;
  titleEnglish: string | null;
  coverExtraLarge: string | null;
  coverLarge: string | null;
  coverMedium: string | null;
  bannerImage: string | null;
  description: string;
  averageScore: number | null;
  chapters: number | null;
  volumes: number | null;
  status: string | null;
  genres: string[];
  year: number | null;
};

export const MANGA_COVERS: Record<string, MangaCover> = {
  "yotsubato": {
    "aniListId": 30104,
    "titleRomaji": "Yotsuba to!",
    "titleNative": "よつばと！",
    "titleEnglish": "Yotsuba&!",
    "coverExtraLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx30104-sUVzNlTWZ5cu.jpg",
    "coverLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30104-sUVzNlTWZ5cu.jpg",
    "coverMedium": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx30104-sUVzNlTWZ5cu.jpg",
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/manga/banner/30104-CDra9ye7UPGI.jpg",
    "description": "Hello! This is Koiwai Yotsuba, Yotsuba Koiwai...um, YOTSUBA! Yotsuba moved with Daddy to a new house from our old house waaaaaaay over there! And moving's fun 'cos people wave! (Ohhhh!!) And Yotsuba met these nice people next door and made friends to play with (one of 'em acted like one of those bad strangers Daddy told Yotsuba not to go with, but it was okay in the end). I hope we get to play a lot. And eat ice cream! And-and-and...oh yeah! You should come play with Yotsuba too!\n\n(Source: Yen Press)\n\nNotes:\n- Includes an interlude.\n- Won the Excellence Award for Manga at the Japan Media Arts Festival in 2006 and the Grand Prize of the 20th Osamu Tezuka Cultural Prize in 2016.\n- Was nominated for the Manga Taishō award in 2008 and for the 12th and 20th Osamu Tezuka Cultural Prize in 2008 and 2016.\n- Was nominated for the Eisner Award in the \"Best Publication for Kids\" category.",
    "averageScore": 88,
    "chapters": null,
    "volumes": null,
    "status": "RELEASING",
    "genres": [
      "Comedy",
      "Slice of Life"
    ],
    "year": 2003
  },
  "doraemon": {
    "aniListId": 31032,
    "titleRomaji": "Doraemon",
    "titleNative": "ドラえもん",
    "titleEnglish": null,
    "coverExtraLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx31032-EnHYnoLVqlWG.jpg",
    "coverLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx31032-EnHYnoLVqlWG.jpg",
    "coverMedium": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx31032-EnHYnoLVqlWG.jpg",
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/manga/banner/31032-n36T4nPIMTT0.jpg",
    "description": "Doraemon, a cat shaped robot which came from the 22nd century in the future, goes back in time in order to help Nobita, a below average lazy kid, to make his life less miserable and improve his descendent's life. With many of Doreamon's gadgets from the future, Nobita's life will never be as the same.",
    "averageScore": 80,
    "chapters": 821,
    "volumes": 45,
    "status": "FINISHED",
    "genres": [
      "Adventure",
      "Comedy",
      "Sci-Fi"
    ],
    "year": 1969
  },
  "frieren": {
    "aniListId": 118586,
    "titleRomaji": "Sousou no Frieren",
    "titleNative": "葬送のフリーレン",
    "titleEnglish": "Frieren: Beyond Journey’s End",
    "coverExtraLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx118586-CXKgWikBFQgS.jpg",
    "coverLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx118586-CXKgWikBFQgS.jpg",
    "coverMedium": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx118586-CXKgWikBFQgS.jpg",
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/manga/banner/118586-R1c7mc72oPvS.jpg",
    "description": "The adventure is over but life goes on for an elf mage just beginning to learn what living is all about.\n\nElf mage Frieren and her courageous fellow adventurers have defeated the Demon King and brought peace to the land. With the great struggle over, they all go their separate ways to live a quiet life. But as an elf, Frieren, nearly immortal, will long outlive the rest of her former party. How will she come to terms with the mortality of her friends? How can she find fulfillment in her own life, and can she learn to understand what life means to the humans around her? Frieren begins a new journey to find the answer.\n\n(Source: VIZ Media)\n\nNotes:\n- Winner of the Grand Prize at the 14th Manga Taisho Awards.\n- Nominated for the 25th Annual Tezuka Osamu Cultural Prize.\n- Placed 3rd at the 7th Annual Next Manga Award.",
    "averageScore": 87,
    "chapters": null,
    "volumes": null,
    "status": "RELEASING",
    "genres": [
      "Adventure",
      "Drama",
      "Fantasy"
    ],
    "year": 2020
  },
  "spy-x-family": {
    "aniListId": 108556,
    "titleRomaji": "SPY×FAMILY",
    "titleNative": "SPY×FAMILY",
    "titleEnglish": "SPY x FAMILY",
    "coverExtraLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx108556-NHjkz0BNJhLx.jpg",
    "coverLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx108556-NHjkz0BNJhLx.jpg",
    "coverMedium": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx108556-NHjkz0BNJhLx.jpg",
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/manga/banner/108556-iCiPfU0GU4OM.jpg",
    "description": "The master spy codenamed <Twilight> has spent his days on undercover missions, all for the dream of a better world. But one day, he receives a particularly difficult new order from command. For his mission, he must form a temporary family and start a new life?! A Spy/Action/Comedy about a one-of-a-kind family!\n\n(Source: MANGA Plus)\n\nNotes:\n- Nominated for the 24th Tezuka Osamu Cultural Prize in 2020.\n- Nominated for the 13th and 14th Manga Taisho Award in 2020 and 2021.\n- Nominated for the 44th Kodansha Manga Award in the Shounen Category in 2020.",
    "averageScore": 83,
    "chapters": null,
    "volumes": null,
    "status": "RELEASING",
    "genres": [
      "Action",
      "Comedy",
      "Slice of Life",
      "Supernatural"
    ],
    "year": 2019
  },
  "mob-psycho-100": {
    "aniListId": 85189,
    "titleRomaji": "Mob Psycho 100",
    "titleNative": "モブサイコ100",
    "titleEnglish": "Mob Psycho 100",
    "coverExtraLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/nx85189-06aXUBq5jwce.jpg",
    "coverLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx85189-06aXUBq5jwce.jpg",
    "coverMedium": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/nx85189-06aXUBq5jwce.jpg",
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/manga/banner/85189-x3AUm32RKfwG.jpg",
    "description": "Do you or someone you know need an exorcist who works cheap? Reigen's your guy! What's his secret to busting ghosts while keeping prices low? Well, first, he's a fraud, and second, he pays the guy who's got the real psychic power, his student assistant Shigeo, less than minimum wage. Shigeo is an awkward but kind boy whose urge to help others and get along with them is bound up with the mental safety locks he's placed on his own emotions. Reigen knows he needs to exploit Shigeo to stay in business, yet for better or worse he's also his mentor and counselor. And he also knows whenever the normally repressed kid's emotions reach level 100, it may unleash more psychic energy than either of them can handle!\n\n(Source: Dark Horse)\n\nNote: Includes 12 extra chapters.",
    "averageScore": 85,
    "chapters": 113,
    "volumes": 16,
    "status": "FINISHED",
    "genres": [
      "Action",
      "Comedy",
      "Drama",
      "Psychological",
      "Slice of Life",
      "Supernatural"
    ],
    "year": 2012
  },
  "pluto": {
    "aniListId": 30745,
    "titleRomaji": "PLUTO",
    "titleNative": "PLUTO",
    "titleEnglish": "Pluto",
    "coverExtraLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx30745-kueBpwriQkvZ.jpg",
    "coverLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30745-kueBpwriQkvZ.jpg",
    "coverMedium": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx30745-kueBpwriQkvZ.jpg",
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/manga/banner/30745-vC3JZQjHPwhn.jpg",
    "description": "In an ideal world where man and robots coexist, someone or something has destroyed the powerful Swiss robot Mont Blanc. Elsewhere a key figure in a robot rights group is murdered. The two incidents appear to be unrelated...except for one very conspicuous clue - the bodies of both victims have been fashioned into some sort of bizarre collage complete with makeshift horns placed by the victims' heads. Interpol assigns robot detective Gesicht to this most strange and complex case - and he eventually discovers that he too, as one of the seven great robots of the world, is one of the targets.\n\n(Source: VIZ Media)",
    "averageScore": 85,
    "chapters": 65,
    "volumes": 8,
    "status": "FINISHED",
    "genres": [
      "Drama",
      "Mecha",
      "Mystery",
      "Psychological",
      "Sci-Fi"
    ],
    "year": 2003
  },
  "attack-on-titan": {
    "aniListId": 53390,
    "titleRomaji": "Shingeki no Kyojin",
    "titleNative": "進撃の巨人",
    "titleEnglish": "Attack on Titan",
    "coverExtraLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx53390-1RsuABC34P9D.jpg",
    "coverLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx53390-1RsuABC34P9D.jpg",
    "coverMedium": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx53390-1RsuABC34P9D.jpg",
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/manga/banner/53390-6Uru5rrjh8zv.jpg",
    "description": "In this post-apocalyptic sci-fi story, humanity has been devastated by the bizarre, giant humanoids known as the Titans. Little is known about where they came from or why they are bent on consuming mankind. Seemingly unintelligent, they have roamed the world for years, killing everyone they see. For the past century, what's left of man has hidden in a giant, three-walled city. People believe their 50-meter-high walls will protect them from the Titans, but the sudden appearance of an immense Titan is about to change everything.\n\n(Source: Kodansha USA)\n\nNote: Includes two extra chapters.",
    "averageScore": 84,
    "chapters": 141,
    "volumes": 34,
    "status": "FINISHED",
    "genres": [
      "Action",
      "Drama",
      "Fantasy",
      "Mystery"
    ],
    "year": 2009
  },
  "death-note": {
    "aniListId": 30021,
    "titleRomaji": "DEATH NOTE",
    "titleNative": "DEATH NOTE",
    "titleEnglish": "Death Note",
    "coverExtraLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx30021-FE6kmrfpuKyb.jpg",
    "coverLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30021-FE6kmrfpuKyb.jpg",
    "coverMedium": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx30021-FE6kmrfpuKyb.jpg",
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/manga/banner/n30021-eZbrTpIjv10E.jpg",
    "description": "Light Yagami is an ace student with great prospects, and he’s bored out of his mind. But all that changes when he finds the Death Note, a notebook dropped by a rogue Shinigami death god. Any human whose name is written in the notebook dies, and Light has vowed to use the power of the Death Note to rid the world of evil. But will Light succeed in his noble goal, or will the Death Note turn him into the very thing he fights against?\n\n(Source: VIZ Media)",
    "averageScore": 84,
    "chapters": 108,
    "volumes": 12,
    "status": "FINISHED",
    "genres": [
      "Drama",
      "Mystery",
      "Psychological",
      "Supernatural",
      "Thriller"
    ],
    "year": 2003
  },
  "monster": {
    "aniListId": 30001,
    "titleRomaji": "MONSTER",
    "titleNative": "MONSTER",
    "titleEnglish": "Monster",
    "coverExtraLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx30001-Knby7l1jevE7.jpg",
    "coverLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30001-Knby7l1jevE7.jpg",
    "coverMedium": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx30001-Knby7l1jevE7.jpg",
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/manga/banner/1-x9ksIvb9cKK2.jpg",
    "description": "Everyone faces uncertainty at some point in their lives. Even a brilliant surgeon like Kenzo Tenma is no exception. But there’s no way he could have known that his decision to stop chasing professional success and instead concentrate on his oath to save peoples’ lives would result in the birth of an abomination. The questions of good and evil now take on a terrifyingly real dimension.\n\nYears later, in Germany during the tumultuous post-reunification period, middle-aged childless couples are being killed one after another. The serial killer’s identity is known. The reasons why he kills are not. Dr. Tenma sets out on a journey to find the killer’s twin sister, who may hold some clues to solving the enigma of the “Monster.”\n\n(Source: VIZ Media)",
    "averageScore": 90,
    "chapters": 162,
    "volumes": 18,
    "status": "FINISHED",
    "genres": [
      "Drama",
      "Mystery",
      "Psychological",
      "Thriller"
    ],
    "year": 1994
  },
  "20th-century-boys": {
    "aniListId": 30003,
    "titleRomaji": "20 Seiki Shounen",
    "titleNative": "20世紀少年",
    "titleEnglish": "20th Century Boys",
    "coverExtraLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx30003-E84fwIh22LAQ.jpg",
    "coverLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30003-E84fwIh22LAQ.jpg",
    "coverMedium": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx30003-E84fwIh22LAQ.jpg",
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/manga/banner/30003-MBm3u1K1uHsi.jpg",
    "description": "Humanity, having faced extinction at the end of the 20th century, would not have entered the new millennium if it weren't for them. In 1969, during their youth, they created a symbol. In 1997, as the coming disaster slowly starts to unfold, that symbol returns. This is the story of a group of boys who try to save the world.\n\nFor Kenji, a simple convenience store manager who once dreamed of becoming a rock 'n' roll musician, a host of memories from his past come rushing back when one of his childhood friends mysteriously commits suicide. Could this new death be related to the rise of a bizarre new cult that's been implicated in several other murders and disappearances? Determined to dig deeper, Kenji reunites with some of his old buddies in the hope of learning the truth behind it all.\n\n(Source: VIZ Media)",
    "averageScore": 88,
    "chapters": 249,
    "volumes": 22,
    "status": "FINISHED",
    "genres": [
      "Drama",
      "Mystery",
      "Psychological",
      "Sci-Fi",
      "Thriller"
    ],
    "year": 1999
  },
  "vinland-saga": {
    "aniListId": 30642,
    "titleRomaji": "Vinland Saga",
    "titleNative": "ヴィンランド・サガ",
    "titleEnglish": "Vinland Saga",
    "coverExtraLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx30642-0mjRDkf4THpo.jpg",
    "coverLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30642-0mjRDkf4THpo.jpg",
    "coverMedium": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx30642-0mjRDkf4THpo.jpg",
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/manga/banner/30642-MeizzL2WDv6C.jpg",
    "description": "As a child, Thorfinn sat at the feet of the great Leif Ericson and thrilled to wild tales of a land far to the west. But his youthful fantasies were shattered by a mercenary raid. Raised by the Vikings who murdered his father, Thorfinn became a terrifying warrior, forever seeking to kill the band's leader, Askeladd, and avenge his father. Sustaining Thorfinn through his ordeal are his pride in his family and his dreams of a fertile westward land, a land without war or slavery … the land Leif called Vinland.\n\n(Source: Kodansha USA)\n\nNotes:\n- Won the Grand Prize at the Japan Media Arts Festival in 2009.\n- Winner of the 36th Kodansha Manga Award in the General category in 2012.",
    "averageScore": 90,
    "chapters": 220,
    "volumes": 29,
    "status": "FINISHED",
    "genres": [
      "Action",
      "Adventure",
      "Drama"
    ],
    "year": 2005
  },
  "berserk": {
    "aniListId": 30002,
    "titleRomaji": "Berserk",
    "titleNative": "ベルセルク",
    "titleEnglish": "Berserk",
    "coverExtraLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx30002-Cul4OeN7bYtn.jpg",
    "coverLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30002-Cul4OeN7bYtn.jpg",
    "coverMedium": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/bx30002-Cul4OeN7bYtn.jpg",
    "bannerImage": "https://s4.anilist.co/file/anilistcdn/media/manga/banner/30002-3TuoSMl20fUX.jpg",
    "description": "His name is Guts, the Black Swordsman, a feared warrior spoken of only in whispers. Bearer of a gigantic sword, an iron hand, and the scars of countless battles and tortures, his flesh is also indelibly marked with The Brand, an unholy symbol that draws the forces of darkness to him and dooms him as their sacrifice. But Guts won't take his fate lying down; he'll cut a crimson swath of carnage through the ranks of the damned, and anyone else foolish enough to oppose him! Accompanied by Puck the Elf, more an annoyance than a companion, Guts relentlessly follows a dark, bloodstained path that leads only to death...or vengeance.\n\n(Source: Dark Horse)\n\nNotes:\n- Volumes 1-5 contain the 16 prequel chapters 0A - 0P.\n- Chapter 83 was omitted from Volume 13 due to the author’s request.\n- Volume 14 includes “Berserk: The Prototype”.\n- Due to the author's passing, starting from Chapter 365, the manga is illustrated by Studio Gaga (Miura's assistants) and supervised by Kouji Mori (a close friend of Miura's).",
    "averageScore": 92,
    "chapters": null,
    "volumes": null,
    "status": "RELEASING",
    "genres": [
      "Action",
      "Adventure",
      "Drama",
      "Fantasy",
      "Horror",
      "Psychological"
    ],
    "year": 1989
  }
};
